### ISSUE TITLE
polytexnic/preprocessors/html.rb:146:in `+': no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by atsaloli** [softcover/softcover#145]
I'm getting this error trying to build EPUB & MOBI.  HTML builds just fine!  Any suggestions?

```
$ softcover build:all
Building all formats...
Building EPUB & MOBI...
/var/lib/gems/2.1.0/gems/polytexnic-1.1.9/lib/polytexnic/preprocessors/html.rb:146:in `+': no implicit conversion of nil into String (TypeError)
	from /var/lib/gems/2.1.0/gems/polytexnic-1.1.9/lib/polytexnic/preprocessors/html.rb:146:in `add_commands'
	from /var/lib/gems/2.1.0/gems/polytexnic-1.1.9/lib/polytexnic/preprocessors/html.rb:48:in `clean_document'
	from /var/lib/gems/2.1.0/gems/polytexnic-1.1.9/lib/polytexnic/preprocessors/html.rb:25:in `process_for_tralics'
	from /var/lib/gems/2.1.0/gems/polytexnic-1.1.9/lib/polytexnic/preprocessors/html.rb:12:in `to_xml'
	from /var/lib/gems/2.1.0/gems/polytexnic-1.1.9/lib/polytexnic/preprocessor.rb:18:in `preprocess'
	from /var/lib/gems/2.1.0/gems/polytexnic-1.1.9/lib/polytexnic.rb:86:in `to_html'
	from /var/lib/gems/2.1.0/gems/softcover-1.1.15/lib/softcover/book_manifest.rb:65:in `html_title'
	from /var/lib/gems/2.1.0/gems/softcover-1.1.15/lib/softcover/builders/epub.rb:544:in `nav_link'
	from /var/lib/gems/2.1.0/gems/softcover-1.1.15/lib/softcover/builders/epub.rb:536:in `block in nav_html'
	from /var/lib/gems/2.1.0/gems/softcover-1.1.15/lib/softcover/builders/epub.rb:535:in `map'
	from /var/lib/gems/2.1.0/gems/softcover-1.1.15/lib/softcover/builders/epub.rb:535:in `nav_html'
	from /var/lib/gems/2.1.0/gems/softcover-1.1.15/lib/softcover/builders/epub.rb:449:in `write_nav'
	from /var/lib/gems/2.1.0/gems/softcover-1.1.15/lib/softcover/builders/epub.rb:145:in `build!'
	from /var/lib/gems/2.1.0/gems/softcover-1.1.15/lib/softcover/builders/mobi.rb:8:in `build!'
	from /var/lib/gems/2.1.0/gems/softcover-1.1.15/lib/softcover/commands/build.rb:30:in `block in all_formats'
	from /var/lib/gems/2.1.0/gems/softcover-1.1.15/lib/softcover/commands/build.rb:24:in `each'
	from /var/lib/gems/2.1.0/gems/softcover-1.1.15/lib/softcover/commands/build.rb:24:in `all_formats'
	from /var/lib/gems/2.1.0/gems/softcover-1.1.15/lib/softcover/cli.rb:28:in `build'
	from /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /var/lib/gems/2.1.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /var/lib/gems/2.1.0/gems/softcover-1.1.15/bin/softcover:4:in `<top (required)>'
	from /usr/local/bin/softcover:23:in `load'
	from /usr/local/bin/softcover:23:in `<main>'
$ 
```

**Comment by mhartl** [comment]
The ebooks for your repo build fine on my system, so I think this is still a Tralics issue. I'm closing this out under that assumption and will reopen if necessary.
