### ISSUE TITLE
Failing to build epub/mobi with unknown file type: html/images

### ISSUE THREAD

**Issue by nickjj** [softcover/softcover#186]
I'm able to build the PDF and HTML versions of the book but epub/mobi both fail with this stack trace:

```ruby
tmp $ softcover build
Building all formats...
Building EPUB & MOBI...
/home/nick/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:1387:in `copy': unknown file type: html/images (RuntimeError)
	from /home/nick/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:472:in `block in copy_entry'
	from /home/nick/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:1498:in `wrap_traverse'
	from /home/nick/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:469:in `copy_entry'
	from /home/nick/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:444:in `block in cp_r'
	from /home/nick/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:1571:in `block in fu_each_src_dest'
	from /home/nick/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:1585:in `fu_each_src_dest0'
	from /home/nick/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:1569:in `fu_each_src_dest'
	from /home/nick/.rubies/ruby-2.3.0/lib/ruby/2.3.0/fileutils.rb:443:in `cp_r'
	from /home/nick/.gem/ruby/2.3.0/gems/softcover-1.4.3/lib/softcover/builders/epub.rb:445:in `copy_image_files'
	from /home/nick/.gem/ruby/2.3.0/gems/softcover-1.4.3/lib/softcover/builders/epub.rb:158:in `build!'
	from /home/nick/.gem/ruby/2.3.0/gems/softcover-1.4.3/lib/softcover/builders/mobi.rb:8:in `build!'
	from /home/nick/.gem/ruby/2.3.0/gems/softcover-1.4.3/lib/softcover/commands/build.rb:30:in `block in all_formats'
	from /home/nick/.gem/ruby/2.3.0/gems/softcover-1.4.3/lib/softcover/commands/build.rb:24:in `each'
	from /home/nick/.gem/ruby/2.3.0/gems/softcover-1.4.3/lib/softcover/commands/build.rb:24:in `all_formats'
	from /home/nick/.gem/ruby/2.3.0/gems/softcover-1.4.3/lib/softcover/cli.rb:28:in `build'
	from /home/nick/.gem/ruby/2.3.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /home/nick/.gem/ruby/2.3.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /home/nick/.gem/ruby/2.3.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /home/nick/.gem/ruby/2.3.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /home/nick/.gem/ruby/2.3.0/gems/softcover-1.4.3/bin/softcover:4:in `<top (required)>'
	from /home/nick/.gem/ruby/2.3.0/bin/softcover:23:in `load'
	from /home/nick/.gem/ruby/2.3.0/bin/softcover:23:in `<main>'
```
The really weird thing is that the book was successfully built for epub/mobi formats in the past. Nothing changed other than time. All I did was change 1 sentence in the book and tried to re-build.

**Comment by nickjj** [comment]
I followed the stack trace to this line of code: https://github.com/softcover/softcover/blob/master/lib/softcover/builders/epub.rb#L445

Then noticed I didn't have an `html/images` directory in my project so I added it, and now it all works. I'm pretty sure I never manually deleted that folder, but I thought I'd add this here in case someone else happens to get the same problem in the future.
