### ISSUE TITLE
Publishing error: Incompatible library version

### ISSUE THREAD

**Issue by cavalryjim** [softcover/softcover#191]
Following the softcover manual, I try to publish (section 1.2.2) and receive an 'Incompatible library version' error.

```
james$ softcover publish
Publishing...
/Users/james/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/james/.rvm/gems/ruby-2.2.2@softcover/gems/curb-0.8.8/lib/curb_core.bundle, 9): Library not loaded: @rpath/libcurl.4.dylib (LoadError)
  Referenced from: /Users/james/.rvm/gems/ruby-2.2.2@softcover/gems/curb-0.8.8/lib/curb_core.bundle
  Reason: Incompatible library version: curb_core.bundle requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0 - /Users/james/.rvm/gems/ruby-2.2.2@softcover/gems/curb-0.8.8/lib/curb_core.bundle
	from /Users/james/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/james/.rvm/gems/ruby-2.2.2@softcover/gems/curb-0.8.8/lib/curl.rb:1:in `<top (required)>'
	from /Users/james/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/james/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/james/.rvm/gems/ruby-2.2.2@softcover/gems/curb-0.8.8/lib/curb.rb:1:in `<top (required)>'
	from /Users/james/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/james/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/james/.rvm/gems/ruby-2.2.2@softcover/gems/softcover-1.4.5/lib/softcover/commands/publisher.rb:12:in `publish!'
	from /Users/james/.rvm/gems/ruby-2.2.2@softcover/gems/softcover-1.4.5/lib/softcover/cli.rb:154:in `publish'
	from /Users/james/.rvm/gems/ruby-2.2.2@softcover/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	from /Users/james/.rvm/gems/ruby-2.2.2@softcover/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	from /Users/james/.rvm/gems/ruby-2.2.2@softcover/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	from /Users/james/.rvm/gems/ruby-2.2.2@softcover/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	from /Users/james/.rvm/gems/ruby-2.2.2@softcover/gems/softcover-1.4.5/bin/softcover:4:in `<top (required)>'
	from /Users/james/.rvm/gems/ruby-2.2.2@softcover/bin/softcover:23:in `load'
	from /Users/james/.rvm/gems/ruby-2.2.2@softcover/bin/softcover:23:in `<main>'
	from /Users/james/.rvm/gems/ruby-2.2.2@softcover/bin/ruby_executable_hooks:15:in `eval'
	from /Users/james/.rvm/gems/ruby-2.2.2@softcover/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by mhartl** [comment]
@nickmerwin Any idea what might be going on here?

**Comment by cavalryjim** [comment]
Solved the problem by reinstalling curl.

```
brew install curl
brew ln curl --force
```
