### ISSUE TITLE
Use custom lexers with Pygments

### ISSUE THREAD

**Issue by areiterer** [softcover/softcover#193]
I installed a custom lexer _pygments-lexer-babylon_ with 
`pip install pygments-lexer-babylon` to support JSX syntax formatting. 

`pygmentize myfile.jsx` provides the correct output, therefore I assume it installed correctly. 

Unfortunately, when trying to build my book with a JSX snippet, I run into an error when building the book, see below stack trace. 

I'm not sure if this is the right place to ask, but since it works by calling pygments directly, I hope for the best. Is there something else I could provide? 

```
Building.../Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:405:in `header_to_json': Traceback (most recent call last): (MentosError)
  File "/Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 303, in start
    res = self.get_data(method, lexer, args, kwargs, text)
  File "/Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 171, in get_data
    res = self.highlight_text(text, lexer, formatter_name, args, _convert_keys(opts))
  File "/Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 122, in highlight_text
    lexer = self.return_lexer(lexer, args, kwargs, code)
  File "/Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 79, in return_lexer
    return lexers.get_lexer_by_name(lexer, **inputs)
  File "/Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/vendor/pygments-main/pygments/lexers/__init__.py", line 95, in get_lexer_by_name
    for cls in find_plugin_lexers():
  File "/Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/vendor/pygments-main/pygments/plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/pygmentslexerbabylon/__init__.py", line 1, in <module>
    from .lexer import BabylonLexer, BabylonHtmlLexer  # noqa
  File "/Library/Python/2.7/site-packages/pygmentslexerbabylon/lexer.py", line 8, in <module>
    from pygments.lexers.html import HtmlLexer
ImportError: No module named html
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:287:in `handle_header_and_return'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:262:in `block in mentos'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/2.3.0/timeout.rb:33:in `catch'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/2.3.0/timeout.rb:33:in `catch'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:233:in `mentos'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:215:in `highlight'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/polytexnic-1.3.5/lib/polytexnic/utils.rb:209:in `highlight'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/polytexnic-1.3.5/lib/polytexnic/utils.rb:170:in `block in highlight_source_code'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/node_set.rb:190:in `block in each'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/node_set.rb:189:in `upto'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/nokogiri-1.8.1/lib/nokogiri/xml/node_set.rb:189:in `each'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/polytexnic-1.3.5/lib/polytexnic/utils.rb:166:in `highlight_source_code'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/polytexnic-1.3.5/lib/polytexnic/postprocessors/html.rb:1295:in `convert_to_html'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/polytexnic-1.3.5/lib/polytexnic/postprocessors/html.rb:61:in `xml_to_html'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/polytexnic-1.3.5/lib/polytexnic/postprocessor.rb:16:in `postprocess'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/polytexnic-1.3.5/lib/polytexnic.rb:91:in `to_html'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/softcover-1.4.9/lib/softcover/builders/html.rb:123:in `converted_html'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/softcover-1.4.9/lib/softcover/builders/html.rb:43:in `build'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/softcover-1.4.9/lib/softcover/commands/server.rb:47:in `rebuild'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/softcover-1.4.9/lib/softcover/commands/server.rb:63:in `run'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/softcover-1.4.9/lib/softcover/cli.rb:106:in `server'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /Users/andreas/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/softcover-1.4.9/bin/softcover:4:in `<top (required)>'
        from /Users/andreas/.rbenv/versions/2.3.5/bin/softcover:22:in `load'
        from /Users/andreas/.rbenv/versions/2.3.5/bin/softcover:22:in `<main>'
```

**Comment by mhartl** [comment]
Unfortunately, I don't see offhand how to adapt Softcover to use the custom lexer. Sorry I can't be more helpful.

**Comment by areiterer** [comment]
Thank you anyway. If I find a solution, I'm adding a comment here 🙂
