### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by mplatts** [softcover/softcover#212]
Mac Catalina 10.15.3
Using RVM
Ruby version 2.6.3

```
~/D/e/phoenix-tutorial ❯❯❯ softcover login
Logging in.
Email: plattsmw@gmail.com
Password (won't be shown):
Traceback (most recent call last):
	17: from /Users/mplatts/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	16: from /Users/mplatts/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	15: from /Users/mplatts/.rvm/gems/ruby-2.6.3/bin/softcover:23:in `<main>'
	14: from /Users/mplatts/.rvm/gems/ruby-2.6.3/bin/softcover:23:in `load'
	13: from /Users/mplatts/.rvm/gems/ruby-2.6.3/gems/softcover-1.6.1/bin/softcover:4:in `<top (required)>'
	12: from /Users/mplatts/.rvm/gems/ruby-2.6.3/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
	11: from /Users/mplatts/.rvm/gems/ruby-2.6.3/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
	10: from /Users/mplatts/.rvm/gems/ruby-2.6.3/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
	 9: from /Users/mplatts/.rvm/gems/ruby-2.6.3/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
	 8: from /Users/mplatts/.rvm/gems/ruby-2.6.3/gems/softcover-1.6.1/lib/softcover/cli.rb:123:in `login'
	 7: from /Users/mplatts/.rvm/gems/ruby-2.6.3/gems/softcover-1.6.1/lib/softcover/commands/auth.rb:9:in `login'
	 6: from /Users/mplatts/.rvm/gems/ruby-2.6.3/gems/softcover-1.6.1/lib/softcover/client.rb:36:in `login!'
	 5: from /Users/mplatts/.rvm/gems/ruby-2.6.3/gems/softcover-1.6.1/lib/softcover/client.rb:83:in `block (2 levels) in <class:Client>'
	 4: from /Users/mplatts/.rvm/gems/ruby-2.6.3/gems/rest-client-1.8.0/lib/restclient.rb:69:in `post'
	 3: from /Users/mplatts/.rvm/gems/ruby-2.6.3/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'
	 2: from /Users/mplatts/.rvm/gems/ruby-2.6.3/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `new'
	 1: from /Users/mplatts/.rvm/gems/ruby-2.6.3/gems/rest-client-1.8.0/lib/restclient/request.rb:163:in `initialize'
/Users/mplatts/.rvm/gems/ruby-2.6.3/gems/rest-client-1.8.0/lib/restclient/request.rb:163:in `fetch': key not found: :ciphers (KeyError)
```

**Comment by mplatts** [comment]
fixed it by just updating restclient 🤦‍♂
